server:
  port: 8081
spring:
  dubbo:
     application:
        id:
           sys-provider
        name:
           sys-provider
     registry:
        address:
            zookeeper://127.0.0.1:2181
     server:
        true
     protocol:
        name:
           dubbo
        port:
           20880
        threads:
           100


