server:
  port: 8082
spring:
   # 环境 dev|test|pro
  profiles:
     active:
        dev
  dubbo:
     application:
        id:
           sys-consumer
        name:
           sys-consumer
     registry:
        address:
            zookeeper://127.0.0.1:2181
     protocol:
        name:
           dubbo
        port:
           20880
        threads:
           100
     scan:
         com.caisc
     packageName:
         com.caisc


